name: Deploy V4 Site

on:
  push:
    branches: [next]
    paths:
      - 'packages/vant/docs/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: 'next'

      - name: Install pnpm
        run: npm i pnpm@7 -g

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Site
        run: npm run build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: packages/vant/site-dist
          target-folder: v4
          clean: false
